### ISSUE TITLE
Detailed endpoitns for titles

### ISSUE THREAD

**Issue by DomiiBunn** [BunnyWare/Watchy-Backend#2]
- [x] `/api/tmdb/tv/{{tvID}}/` - gets series details
- [x] `/api/tmdb/tv{{tvID}}/season/{{seasonID}}` - gets details for a preticular season
- [x] `/api/tmdb/tv/{{tvID}}/seasons/` - gets season name and ids for a series
- [x] `/api/tmdb/tv/{{tvID}}episodes/` - gets a list of episodes
- [x] `/api/tmdb/tv/{{tvID}}/episode/{{episodeID}}` - gets details for a preticular episode
- [x] `/api/tmdb/movie/{{movieID}}/` - gets movie details

**Comment by FayeDE** [comment]
That's already present, isn't it?

**Comment by DomiiBunn** [comment]
Yeah the issue was created before it was implemented I think
